### ISSUE TITLE
logo for DogTracker

### ISSUE THREAD

**Issue by hafizahmmed** [natron2244/DogTracker#2]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![dogtracker-01](https://user-images.githubusercontent.com/38810169/41250900-1626cc92-6dda-11e8-9a08-40a57c5f5283.jpg)

Thank you

**Comment by natron2244** [comment]
Hey Hafiz,

Thanks a lot. Yeah I would be interested. To confirm you created the icon and it free to use?

Thanks,
-Nathan

**Comment by hafizahmmed** [comment]
yes sir. can i make a pull request ??

Thank you

**Comment by natron2244** [comment]
Yep.

**Comment by hafizahmmed** [comment]
please check #6

https://drive.google.com/open?id=1gzj--rbEeqeUwJnKOKMkVfvh29Oos0Xh

**Comment by natron2244** [comment]
Merged to master, closing issue.
